# Generated by Django 5.2.6 on 2025-09-04 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('banner', models.ImageField(blank=True, db_column='logo', null=True, upload_to='events/banners/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(help_text='Where attendees are sent when the session is live')),
                ('color', models.BigIntegerField(blank=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evt_event',
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['start_at'], name='evt_event_start_a_94c9b3_idx'), models.Index(fields=['end_at'], name='evt_event_end_at_566326_idx'), models.Index(fields=['code', 'is_current'], name='evt_event_code_b94a8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('REGISTRATION', 'Registrations'), ('EVENT', 'Events'), ('ANALYTICS', 'Analytics')], max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('include_all', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evt_generated_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('speciality', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventExpert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120, null=True)),
                ('photo', models.ImageField(upload_to='events/experts/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='abort_app.event')),
            ],
            options={
                'db_table': 'evt_expert',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['event', 'order'], name='evt_expert_event_i_3efd14_idx')],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EventJoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joins', to='abort_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_joins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evt_join',
                'indexes': [models.Index(fields=['user'], name='evt_join_user_id_1a3077_idx'), models.Index(fields=['event'], name='evt_join_event_i_4a1c5e_idx'), models.Index(fields=['joined_at'], name='evt_join_joined__071f24_idx')],
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='JoinLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('REFUSED', 'Refused'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_logs', to='abort_app.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_attempt_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evt_join_log',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['status', 'occurred_at'], name='evt_join_lo_status_0e49e2_idx'), models.Index(fields=['event', 'occurred_at'], name='evt_join_lo_event_i_e242f8_idx')],
            },
        ),
    ]
