# Generated by Django 5.2.6 on 2025-09-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abort_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
